### PR TITLE
Initial pull back to master

### PR DESCRIPTION
**Pull request by SolomonShorser-OICR**

### CODE REVIEW

**Comment by briandoconnor** [comment]
Some comments/questions for @SolomonShorser-OICR :
- you're missing instructions on how to build and the INI file parameters, you just show how to run with Docker
  - I made some edits to the readme, please fill in more
- how are these used?
  - https://github.com/ICGC-TCGA-PanCancer/OxoGWrapperWorkflow/blob/develop/Dockerfile#L45
  - https://github.com/ICGC-TCGA-PanCancer/OxoGWrapperWorkflow/blob/develop/Dockerfile#L46
- why is this an HTTP URL?  https://github.com/ICGC-TCGA-PanCancer/OxoGWrapperWorkflow/blob/develop/workflow/config/OxoGWrapperWorkflow.ini#L2
- why are these commented out?  https://github.com/ICGC-TCGA-PanCancer/OxoGWrapperWorkflow/blob/develop/workflow/config/OxoGWrapperWorkflow.ini#L35
- shouldn't this (https://github.com/ICGC-TCGA-PanCancer/OxoGWrapperWorkflow/blob/develop/src/main/java/com/github/seqware/OxoGWrapperWorkflow.java#L484) be before combineAllSV?
- https://github.com/ICGC-TCGA-PanCancer/OxoGWrapperWorkflow/blob/develop/src/main/java/com/github/seqware/OxoGWrapperWorkflow.java#L478 is this misnamed?  really this should be variantBamRegionPrep or something similar?
- Are https://github.com/ICGC-TCGA-PanCancer/OxoGWrapperWorkflow/blob/develop/src/main/java/com/github/seqware/OxoGWrapperWorkflow.java#L490 and the line after setup to run in parallel with oxoG?  Would that give a performance boost?
- https://github.com/ICGC-TCGA-PanCancer/OxoGWrapperWorkflow/blob/develop/src/main/java/com/github/seqware/OxoGWrapperWorkflow.java#L371 indent format is messed up
- where do you pass in your credentials for rsync? https://github.com/ICGC-TCGA-PanCancer/OxoGWrapperWorkflow/blob/develop/src/main/java/com/github/seqware/OxoGWrapperWorkflow.java#L440

**Comment by briandoconnor** [comment]
One more comment... lots of commented out code.  Please delete if it's to be removed e.g.:  https://github.com/ICGC-TCGA-PanCancer/OxoGWrapperWorkflow/blob/develop/src/main/java/com/github/seqware/OxoGWrapperWorkflow.java#L255

**Comment by briandoconnor** [comment]
Solomon, fill in the details in the README... I tried to flesh it out but if needs a pass by you: 

https://github.com/ICGC-TCGA-PanCancer/OxoGWrapperWorkflow/commit/85f44089248ef4a872b967d2a1728280eca12b75

**Comment by SolomonShorser-OICR** [comment]
RE: the README - yes, it's gotten rather out-of-date. Once the code stabilizes I'd like to add quite a bit more detail to it. I felt that it was changing too quickly for a while. Hopefully that will end soon...

RE: OXOG_WRAPPER_IMAGE_VERSION and OXOG_WRAPPER_IMAGE_VERSION - those were intended to make it easier to inspect a container/image and know what it was.

RE: the HTTP url for upload - that was an example that I put in there way back and haven't changed yet.

RE: the commented out settings in the INI - they are optional. A user doesn't _need_ to use them as I felt that they could be defaulted, but they can be changed if a user wants.

RE: the ordering of move2running and combineAllSVs - a good question. Some of the pre-processing steps happen in the same functions that do the download, and I considered "running" to be running OxoG/variant-bam. I can move the pre-processing steps to be part of "running". And yes, it's probably mis-named - there used to be three separate jobs that were "combine-by-type" but since your script does them all, it's not necessary to have three separate jobs. It will be renamed.

RE: running the OxoG processes at the same time as the variantbam processes - yes the intention was to run them in parallel. The variantbam processes never use more than one core and even when running together they don't seem to slow each other down _too_ much so I intended to run them at the same time as the OxoG processes, but the OxoG processes may use several cores at certain times so they will run in serial.

RE: messed up formatting - Ugh! That _is_ ugly! I'll have a look at running everything through the same formatter. 

RE: rsync credentials - I'm aware that the upload/rsync part is a bit underdeveloped, I've mostly been trying to keep up with keeping the rest of the workflow up to date. As the rest stabilizes, I'm hoping to have a chance to finish this part off.

RE: dead/commented-out code - Yes, I have a cleanup on my to-do list as well.

**Pull request closed without merging**
