### PR TITLE
Feature/get to first run through

### PR DESCRIPTION
**Pull request by SolomonShorser-OICR**
A first run-through of the workflow has been achieved - minus upload, which will need to be worked on later.

### CODE REVIEW

**Comment by briandoconnor** [comment]
Comments as of 2/16:
- Is the INIGenerator going to be run on the command line?   Is that your intent?  Need to be able to give Kyle the jar so he can run this.
- you should make a nice interface on the INIGenerator with command line options e.g. --<options> so Kyle can run this easily
- use the README as a mechanism to hand off to Kyle.  He will need information on how to make INIs from the JSON and also how to construct a docker run command to trigger the workflow.  Include things like where to mount his GNOS/rsync keys.  I think you have this, take another pass at the README, though, since there are places where more info would be useful.
- make sure you lock down the release version strings for the workflow/docker and sync them.  First release is 1.0.0 and the docker build command in the README should be coordinated to use this as well.
- for download make sure it's flexible so that Kyle can use local BAMs (he probably has a cache) and just uses gtdownload for the VCFs
- also, make it possible to download BAM from CGHub

**Comment by SolomonShorser-OICR** [comment]
Yes, the INI generator can be run from the command line. It takes exactly one argument, which is the name of a JSON file to generate an INI for. My idea was to call it in a bash loop on the launcher VM to generate the INI files. Command line options can be added for INI values that the user might want to customize but aren't found in the JSON, but that functionality does not yet exist. 

I will be updating the README once the whole thing is stable.

**Comment by briandoconnor** [comment]
Just FYI, you will likely need to provide additional params to the INI generator, if only to specify GNOS info for CGHub download for Kyle.  You'll want to chat with him to work this out.

**Comment by junjun-zhang** [comment]
Just want to echo @briandoconnor's comment about being able to specify GNOS repo source as alternative download: https://github.com/ICGC-TCGA-PanCancer/OxoGWrapperWorkflow/pull/3#issuecomment-185224783

Is this feature ready, @SolomonShorser-OICR? Do you need anything specific for that in the JSON Job files? The GNOS availability information should already be in the JSON.

**Comment by SolomonShorser-OICR** [comment]
@junjun-zhang: No, that feature has not been started yet. I don't think any additional information is needed in the JSON file, but if anything comes up, I'll let you and Linda know.

The open issue is here: https://github.com/ICGC-TCGA-PanCancer/OxoGWrapperWorkflow/issues/6

**Pull request merged**
